### ISSUE TITLE
Version 7.0.0 release checklist

### ISSUE THREAD

**Issue by Deamon5550** [TVPT/VoxelSniper#265]
- [ ] Brushes
    - [ ] blob
    - [ ] canyon
    - [ ] comet
    - [ ] dome
    - [ ] entity
    - [ ] entity removal
    - [ ] erosion
    - [ ] filldown
    - [ ] ocean
    - [ ] pull
    - [ ] torus
    - [ ] rotation
    - [ ] spline
    - [ ] stencil
    - [ ] stencilList
    - [ ] tree
    - [ ] 3-point circle
- [ ] brush default parameters
- [ ] schematic saving/loading
- [ ] brush presets (saving a brush + parameters under a name)
- [ ] command auto-completion
- [ ] material lists
- [ ] better block state support
- [ ] changing queues to use view workers
- [ ] notification options
- [x] brush process throttling
- [ ] integer based ray tracing
- [ ] persistent region selection
    - [ ] apply brush to region
    - [ ] exclude/include region from operations
- [ ] brush tools
- [ ] clear undo history command
- [ ] throw events
- [x] merge cylinder and disc (add height param to disc)

**Comment by mibby** [comment]
Any update to this? Last time I tried v7, it was completely unusable.

**Comment by Deamon5550** [comment]
[Gunsmith commits](https://github.com/TVPT/VoxelGunsmith/commits/master)
[Sniper commits](https://github.com/TVPT/VoxelSniper/commits/master)

Work is happening.

**Comment by mibby** [comment]
Great. Looking forward to when it is in a useable state. :)

**Comment by DeadlyForest** [comment]
Sadly it seems that it has been 22 days since we got an update. Unless a large update is coming :).

**Comment by gabizou** [comment]
@DeadlyForest please note that VoxelSniper is not the only project that @Deamon5550 works on, let alone has other obligations to tend to, there's quite a few things in other projects that have taken higher priority than working on newer features or adding previously existing brushes (as they all needed to be rewritten for Gunsmith's API).

**Comment by DeadlyForest** [comment]
Yeah, I understand. It is pretty easy to bite off more than you can chew. If I know how VS were coded and knew more on how to code/write plugins than I would volunteer to rewrite it but I still know pretty little on plugins, What are his bigger projects? I'd like to see if there is anything that I could use on my server,

**Comment by gabizou** [comment]
Currently, he's got a few things for school and other work related projects. Otherwise there's the bigger project @SpongePowered's SpongeAPI and implementations (he's written the first phase of the World Generation API and is in the process of writing the second phase for Structure support and native Schematic support).

**Comment by DeadlyForest** [comment]
So sponge is going to be a plugin/mod api like cauldron? That is pretty cool. He should find someone to take over VS for him though.

**Comment by gabizou** [comment]
If you want to suggest someone to take over VoxelSniper's development, tell whoever you think it is to start contributing with PR's. Don't discuss it here in an issue that is meant to be the release checklist.

**Comment by leasoncre** [comment]
status? perms? 

1.9 is out, and we're still waiting on (official) 1.8 support for voxel....

**Comment by Deamon5550** [comment]
@leasoncre 5.170 works fine on 1.8, and probably on 1.9 as well for spigot.
